// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DimensionCreateReq struct {
	Name string `json:"name"`
}

type DimensionListResp struct {
	Items []DimensionResp `json:"items"`
}

type DimensionResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type DimensionUpdateReq struct {
	Name string `json:"name"`
}

type Empty struct {
}

type GroupCreateReq struct {
	Name string `json:"name"`
}

type GroupListResp struct {
	Items []GroupResp `json:"items"`
}

type GroupResp struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	AvgScore  float64 `json:"avgScore"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

type GroupUpdateReq struct {
	Name string `json:"name"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
	ExpireAt    int64  `json:"expireAt"`
}

type MeResp struct {
	Username string `json:"username"`
}

type PageReq struct {
	Page int64 `form:"page,optional" json:"page,optional"`
	Size int64 `form:"size,optional" json:"size,optional"`
}

type RankingReq struct {
	Month       string `form:"month,optional" json:"month,optional"` // YYYY-MM, default current month
	Total       bool   `form:"total,optional" json:"total,optional"` // total ranking (all-time by student.total_score); when true, month/dimensionId are ignored
	DimensionId int64  `form:"dimensionId,optional" json:"dimensionId,optional"`
	TopN        int64  `form:"topN,optional" json:"topN,optional"`
}

type RankingResp struct {
	Items []StudentRankResp `json:"items"`
}

type RecentScoreItemsResp struct {
	Items []ScoreItemResp `json:"items"`
}

type RollcallPickResp struct {
	RoundId   string      `json:"roundId"`
	Student   StudentResp `json:"student"`
	Remaining int64       `json:"remaining"`
}

type RollcallResetReq struct {
	RoundId string `json:"roundId"`
}

type RollcallStartReq struct {
	Fair bool `json:"fair"`
}

type ScoreEntryCreateReq struct {
	Scope       string `json:"scope"`             // student|group|class
	TargetId    int64  `json:"targetId,optional"` // studentId or groupId, when applicable
	ScoreItemId int64  `json:"scoreItemId"`
	Remark      string `json:"remark,optional"`
}

type ScoreEntryListReq struct {
	PageReq
	StudentId int64 `form:"studentId,optional" json:"studentId,optional"`
	GroupId   int64 `form:"groupId,optional" json:"groupId,optional"`
	SinceDays int64 `form:"sinceDays,optional" json:"sinceDays,optional"` // default 30
}

type ScoreEntryListResp struct {
	Total int64            `json:"total"`
	Items []ScoreEntryResp `json:"items"`
}

type ScoreEntryResp struct {
	Id          int64  `json:"id"`
	StudentId   int64  `json:"studentId"`
	GroupId     int64  `json:"groupId"`
	DimensionId int64  `json:"dimensionId"`
	ScoreItemId int64  `json:"scoreItemId"`
	Score       int64  `json:"score"`
	Remark      string `json:"remark"`
	CreatedAt   int64  `json:"createdAt"`
}

type ScoreItemCreateReq struct {
	DimensionId int64  `json:"dimensionId"`
	Name        string `json:"name"`
	Score       int64  `json:"score"`
}

type ScoreItemListReq struct {
	DimensionId int64 `form:"dimensionId,optional" json:"dimensionId,optional"`
}

type ScoreItemListResp struct {
	Items []ScoreItemResp `json:"items"`
}

type ScoreItemResp struct {
	Id          int64  `json:"id"`
	DimensionId int64  `json:"dimensionId"`
	Name        string `json:"name"`
	Score       int64  `json:"score"`
}

type ScoreItemUpdateReq struct {
	DimensionId int64  `json:"dimensionId"`
	Name        string `json:"name"`
	Score       int64  `json:"score"`
}

type StudentCreateReq struct {
	StudentNo string `json:"studentNo"`
	Name      string `json:"name"`
	Gender    string `json:"gender"`
	Phone     string `json:"phone"`
	Position  string `json:"position"`
}

type StudentListReq struct {
	PageReq
	Keyword string `form:"keyword,optional" json:"keyword,optional"`
	GroupId int64  `form:"groupId,optional" json:"groupId,optional"`
}

type StudentListResp struct {
	Total int64         `json:"total"`
	Items []StudentResp `json:"items"`
}

type StudentRankResp struct {
	Rank      int64       `json:"rank"`
	Highlight bool        `json:"highlight"`
	Student   StudentResp `json:"student"`
	Score     int64       `json:"score"`
}

type StudentResp struct {
	Id         int64  `json:"id"`
	StudentNo  string `json:"studentNo"`
	Name       string `json:"name"`
	Gender     string `json:"gender"`
	Phone      string `json:"phone"`
	Position   string `json:"position"`
	GroupId    int64  `json:"groupId"`
	TotalScore int64  `json:"totalScore"`
	CreatedAt  int64  `json:"createdAt"`
	UpdatedAt  int64  `json:"updatedAt"`
}

type StudentUpdateReq struct {
	StudentNo string `json:"studentNo,optional"`
	Name      string `json:"name,optional"`
	Gender    string `json:"gender,optional"`
	Phone     string `json:"phone,optional"`
	Position  string `json:"position,optional"`
	GroupId   int64  `json:"groupId,optional"`
}
