// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"class-management-system/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/me",
				Handler: MeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dimensions",
				Handler: DimensionCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dimensions",
				Handler: DimensionListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/dimensions/:id",
				Handler: DimensionUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/dimensions/:id",
				Handler: DimensionDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/groups",
				Handler: GroupCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups",
				Handler: GroupListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/groups/:id",
				Handler: GroupUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/groups/:id",
				Handler: GroupDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rankings/students",
				Handler: RankingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rankings/students/export",
				Handler: RankingExportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rollcall/pick",
				Handler: RollcallPickHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rollcall/reset",
				Handler: RollcallResetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rollcall/start",
				Handler: RollcallStartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/score-entries",
				Handler: ScoreEntryCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/score-entries",
				Handler: ScoreEntryListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/score-entries/:id",
				Handler: ScoreEntryDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/score-items",
				Handler: ScoreItemCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/score-items",
				Handler: ScoreItemListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/score-items/:id",
				Handler: ScoreItemUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/score-items/:id",
				Handler: ScoreItemDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/score-items/recent",
				Handler: ScoreItemRecentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/students",
				Handler: StudentCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/students",
				Handler: StudentListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/students/:id",
				Handler: StudentGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/students/:id",
				Handler: StudentUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/students/:id",
				Handler: StudentDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/students/import",
				Handler: StudentImportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
